version: '2'

services:
  golang-api:
    build: .
    ports:
        - "8080:8080"
    env_file:
      - env
    depends_on:
      - db

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=go_api
      - MYSQL_USER=go_api_user
      - MYSQL_PASSWORD=password
    tty: true