version: '2'

services:
  golang-api:
    build: .
    ports:
        - "8080:8080"
    env_file:
      - env
    depends_on:
      - db

  db:
    image: mysql
    ports:
    - "3306:3306"
    env_file:
      - env
    tty: true